[tool.poetry]
name = "pdf-bot"
version = "0.1.0"
description = "An AI assistant for PDF files"
authors = ["ivan-pua-tpg <ivan.pua@tpgtelecom.com.au>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain-community = "^0.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
